import 'https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=';
import '../../public/pronia/assets/css/font-awesome.min.css';
import '../../public/pronia/assets/css/Pe-icon-7-stroke.css';
import '../../public/pronia/assets/css/animate.min.css'
import '../../public/pronia/assets/css/swiper-bundle.min.css';
import '../../public/pronia/assets/css/nice-select.css';
import '../../public/pronia/assets/css/magnific-popup.min.css';
import '../../public/pronia/assets/css/ion.rangeSlider.min.css';
import '../../public/pronia/assets/css/style.css';